# Generated by Django 3.0.3 on 2020-02-06 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True
    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pasazerowie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesel', models.CharField(max_length=11)),
                ('imie', models.CharField(max_length=20)),
                ('nazwisko', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Rezerwacje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('id_pasazera',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RezerwacjeApp.Pasazerowie')),
            ],
        ),
    ]
