# Generated by Django 3.0.3 on 2020-02-06 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('RezerwacjeApp', '0004_auto_20200206_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lotniska',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Trasy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miejsce_odlotu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odlot',
                                                     to='RezerwacjeApp.Lotniska')),
                ('miejsce_przylotu',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='przylot',
                                   to='RezerwacjeApp.Lotniska')),
            ],
        ),
    ]
