# Generated by Django 3.0.3 on 2020-02-06 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('RezerwacjeApp', '0005_lotniska_trasy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trasy',
            name='miejsce_odlotu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miejsce_odlotu',
                                    to='RezerwacjeApp.Lotniska'),
        ),
        migrations.AlterField(
            model_name='trasy',
            name='miejsce_przylotu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miejsce_przylotu',
                                    to='RezerwacjeApp.Lotniska'),
        ),
    ]
