# Generated by Django 3.0.3 on 2020-02-06 23:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('RezerwacjeApp', '0006_auto_20200206_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotniska',
            name='nazwa',
            field=models.CharField(max_length=20),
        ),
    ]
