# Generated by Django 3.0.3 on 2020-02-08 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('RezerwacjeApp', '0007_auto_20200207_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_odlotu', models.DateTimeField()),
                ('data_przylotu', models.DateTimeField()),
                ('numer_lotu', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Samoloty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc_miejsc', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Wymagania',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Siedzenia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miejsce', models.IntegerField()),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RezerwacjeApp.Loty')),
                ('pasazer',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RezerwacjeApp.Pasazerowie')),
                (
                'samolot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RezerwacjeApp.Samoloty')),
            ],
        ),
        migrations.AddField(
            model_name='loty',
            name='samolot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RezerwacjeApp.Samoloty'),
        ),
        migrations.AddField(
            model_name='loty',
            name='trasa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RezerwacjeApp.Trasy'),
        ),
    ]
