# Generated by Django 3.0.3 on 2020-02-09 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('RezerwacjeApp', '0009_miejscaspecjalne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siedzenia',
            name='pasazer',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE,
                                    to='RezerwacjeApp.Pasazerowie'),
        ),
    ]
