# Generated by Django 3.0.3 on 2020-02-09 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('RezerwacjeApp', '0010_auto_20200209_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siedzenia',
            name='pasazer',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='RezerwacjeApp.Pasazerowie'),
        ),
    ]
